apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: compute-limits-memory-default
  labels:
    project-onboarding/version: v1
spec:
  labelSelector:
    matchExpressions:
      - key: project-onboarding/managed-by
        operator: Exists
      - key: project-onboarding/compute-limits-memory
        operator: DoesNotExist
  templates:
    - objectTemplate: |
        apiVersion: v1
        kind: ResourceQuota
        metadata:
          name: compute-limits-memory
          namespace: {{ .Name }}
          labels:
            project-onboarding/managed-by: project-onboarding
          annotations:
            description: "Applies default memory resource limits for the namespace due to the absence of 'project-onboarding/compute-limits-memory' label."
        spec:
          hard:
            limits.memory: 1Gi
