kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: project-onboarding
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
