apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-onboarding
commonLabels:
  project-onboarding/managed-by: project-onboarding

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - serviceaccount-token.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
