kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: project-onboarding
subjects:
  - kind: ServiceAccount
    name: project-onboarding
    namespace: <kustomized>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: project-onboarding
