apiVersion: v2
name: cert-manager
description: A Helm chart with cert-manager as subchart
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: cert-manager
    version: ^1
    repository: https://charts.jetstack.io
    alias: cert-manager
    condition: cert-manager.enabled

# https://github.com/SINTEF/cert-manager-webhook-gandi
  - name: cert-manager-webhook-gandi
    version: ^0
    repository: https://sintef.github.io/cert-manager-webhook-gandi
