---
- name: setup local user environment
  hosts: localhost

  vars:
    install_aws_cli: true
    terraform_version: 1.0.11

  tasks:
    - name: Create a directories if they don't exist
      ansible.builtin.file:
        path: "{{item}}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ ansible_env.HOME }}/.local/bin"
        - "{{ ansible_env.HOME }}/.local/share/bash-completion/completions"

    - name: get terraform binary from hashicorp
      get_url:
        url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
        dest: "{{ ansible_env.PWD }}/terraform_{{ terraform_version }}_linux_amd64.zip"
        checksum: "sha256:https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_SHA256SUMS"

    - name: install terraform to .local/bin
      unarchive:
        src: "{{ ansible_env.PWD }}/terraform_{{ terraform_version }}_linux_amd64.zip"
        dest: "{{ ansible_env.HOME }}/.local/bin"

    - name: get latest official openshift-client
      unarchive:
        src: https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
        remote_src: true
        dest: "{{ ansible_env.HOME }}/.local/bin"
        creates: "{{ ansible_env.HOME }}/.local/bin/oc"

    - name: Install openstack libs and tools
      pip:
        extra_args: "--user --upgrade"
        name:
          - python-openstackclient
          - boto3
          - awscli
          - os-client-config

    - name: save bash-completion script for openstack-client
      copy:
        content: "{{ lookup('pipe', 'openstack complete') }}"
        dest: "{{ ansible_env.HOME }}/.local/share/bash-completion/completions/openstack"

    - name: Show checklist
      debug:
        msg: "{{ message.split('\n') }}"
      vars:
        message: |
          Next steps;
            * Adjust settings.yml according to your needs
            * Include $HOME/.local/bin (first) in yor PATH

          Then continue here;
            * ansible-playbook 02-installer-image.yml
