---
- name: setup okd4 cluster
  hosts: localhost

  vars:
    installer_dir: installer

  pre_tasks:
    - include_vars: settings.yml


  tasks:
    - name: Terraform template full cluster
      template:
        src: "cluster.tf.j2"
        dest: "cluster.tf"
      vars:
        okd_boot: 0
        network_name: public
        ignition_url: "dummy" # Part of template but unused since okd_boot=0
        ssh_cidrs: []
        all_ports_cidrs: []
        api_cidrs: []

    - block:
        - name: "terraform apply Full cluster"
          command: "terraform apply -auto-approve "
          register: _terraform_apply
      always:
        - debug:
            msg: "{{ _terraform_apply[item].split('\n') }}"
          with_items: [stdout, stderr]
          when: item in _terraform_apply

    - name: Wait for API to be available
      wait_for:
        port: 6443
        host: "api.{{okd_cluster_name}}.{{okd_base_domain}}"

    - name: Next steps
      debug:
        msg: "{{ message.split('\n') }}"
      vars:
        message: |
          Worker nodes are now provisioned and boot node removed
          worker nodes will ask to join the cluster and you must approve CSR to let that happen
          See https://docs.openshift.com/container-platform/4.9/machine_management/more-rhel-compute.html#installation-approve-csrs_more-rhel-compute
          After that you can run;
          openshift-install --dir=installer wait-for install-complete
          When it returns the cluster shoudl be operational, and it should output an auto generated password for the admins usesr kubeadmin
