- hosts: os_metadata_role=lb
  become: true
  remote_user: ubuntu
  gather_facts: no
  vars:
    lb_be_control_plane_servers: "{{ (groups['role=master']             | default([])) +
                                     (groups['role=boot']               | default([])) +
                                     (groups['os_metadata_role=master'] | default([])) +
                                     (groups['os_metadata_role=boot']   | default([])) }}"
    lb_be_app_servers: "{{ (groups['role=worker']             | default([])) +
                           (groups['os_metadata_role=worker'] | default([])) }}"
  tasks:
    - name: wait for node to come up
      wait_for_connection:
        timeout: 900

    - name: Wait for any possibly running unattended upgrade to finish
      raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

    - name: Install haproxy
      apt:
        name: "haproxy"
        state:  latest
        update_cache: yes

    - name: "Dynamic haproxy config based on inventory from terraform state"
      template:
        src: lb.config.j2
        dest: /etc/haproxy/haproxy.cfg
      notify:
        - restart haproxy

  handlers:
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted
