apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: rolebindings-team
  labels:
    project-onboarding/version: v1
spec:
  labelSelector:
    matchExpressions:
      - key: project-onboarding/managed-by
        operator: Exists
      - key: project-onboarding/team
        operator: Exists
  templates:
    - objectTemplate: |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: team
          namespace: {{ .Name }}
          labels:
            project-onboarding/managed-by: project-onboarding
          annotations:
            description: "Applies team permissions based on namespace label 'project-onboarding/team'"
        subjects:
          - apiGroup: rbac.authorization.k8s.io
            kind: Group
            name: {{ index .Labels "project-onboarding/team" }}
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: admin
